### ISSUE TITLE
peer feedback - choice of priors

### ISSUE THREAD

**Issue by mcooper12** [phys201/icetemp#10]
In your tutorial, you say that a flat prior is appropriate for your linear "m" value and for quadratic "q" and "m" parameters. Is that really true? Is there no theory that could bound that prior to a generous uniform prior or even a positive-definite one?

**Comment by diyaselis** [comment]
There's no prior model or information about the dependence of temperature to depth. Our data shows that it increases with depth. But to constrain the priors to a positive range would compromise to analysis because of bias. We also wanted to assume they would be small because we didn't see a rapid change but again it's connected at looking at the data and for the model to work for any temperature vs depth studies we decided to start with a most general model. 
 However better arguments could be said for the temperature vs time (year) model (e.g. include or exclude global warming), but we will use a nonparametric technique that would take care of it.
