### ISSUE TITLE
peer feedback - priors mismatch

### ISSUE THREAD

**Issue by mcooper12** [phys201/icetemp#11]
In the tutorial notebook you say "we could assume it will be in the expected temperature, at ground level, in the Antarctic, which ranges from -20°C (summer) to -60°C (winter)". This implies to me that you plan on bounding your prior to roughly this range, but you then define your prior on b in the lines below as flat (uniform on -infty to infty).  

Then, in the fit_quad_MCMC() function, you seem to define your priors as uniform on -100 to 100 on all 3 quadratic parameters, not as flat. This seems inconsistent with both statements from the tutorial notebook, so I'm a little confused what the actual desired model is.

**Comment by diyaselis** [comment]
As previously noted, there is no justification for constraining parameters like: q or m. 

However, the intercept parameter b could be generally constrained to the values you mentioned because ordinarily you would expect the temperature in the Antarctic to be within it's normal range. 

That said, make the parameter b a Uniform prior would not do any significant changes to our model. Thus for simplicity we keep it as Flat. 

The role of explaining this range is to give sense of the only prior information we can work with, which is not much.

**Comment by diyaselis** [comment]
For your next comment, `pymc3` did not work well with Flat priors (`pm.Flat()`), so we created a uniform prior with large enough bounds.  We could add some comments...

Model wise they should be Flat priors, computational wise we have to compromise with a large range (-100,100)

**Comment by barkls** [comment]
Did you try defining a starting point for the pymc3 sampling based on a quadratic fit? That might get around the need for artificially setting bounds on the priors. Right now the initial guess in the notebook is (0, 0, 0), which is not expected to be correct. In generaly you should use MCMC for estimating uncertainties and sampling the posterior, *not* for doing an initial fit.

Your MCMC sampling takes a long time to run right now, partially because you have a large number of tuning steps and draws, but the sampling still isn't very good. Hopefully a better starting point will help resolve this as well.

edit: I see that you did this on the actual data, just not on the test data. You should start with a good initial guess for the test data as well, and then you should be able to reduce the number of draws (and especially tuning steps) since the sampling will be better.

edit2: Actually it looks like you use the same initial guess for all datasets, but the initial guess was chosen based on a single dataset. In general you should use a different initial guess for each dataset - this will let pymc3 avoid wasting lots of computational effort to burn in - least squares fitting is a much more efficient algorithm for fitting.

**Comment by amulski** [comment]
Note for collaborators: Relevant code has been moved to `analysis.ipynb`. Changes should be made accordingly.

**Comment by amulski** [comment]
Priors, initial guesses, and sampling continue to be updated as we discuss with the 201 course staff
