### ISSUE TITLE
peer feedback - unclear what tutorial last section does (Gaussian process regression)

### ISSUE THREAD

**Issue by bakerl12** [phys201/icetemp#8]
I do not understand the explanation for the last section "incorporating dataset taken at different times" and do not understand how depth information is included in this analysis (replaced d with t). Perhaps tutorial could benefit from more details on Gaussian process regression.

It does seem interesting to look at all the data over time together and understand the influence of time!

**Comment by diyaselis** [comment]
The overall goal of the notebook is to infer the temperature change in the Antarctic within years of data taking to see if there's evidence of an increment in temperature, presumably due to  global warming. 

However, from our detector we only receive temperature and depth data. We will use the Gaussian process regression to combine the temperature and depth data and extrapolate the temperature at ground level. We will do this for every year of data taking and do another model for time (year) and temperature dependence. 


Moreover, the GPR is our goal for this week, the version of the notebook you took a look at is work in progress. Stay tuned.
